### ISSUE TITLE
Is there a way to see which sample the HT belongs to?

### ISSUE THREAD

**Issue by mariaelf97** [quadram-institute-bioscience/tatajuba#5]
Dear author,

Good day to you!
I am trying to use your tool to identify if certain mutations within a bacterial genome are located anywhere close to a HT.
commands used:
tatajuba version 1.0.4 
`tatajuba -f H37Rv.fasta -g H37Rv.gff N0091.fastq 1-0006.fastq --vcf`

I have a few questions:
1. 1827 out of   1840 (more than half) context+tracts were not found in reference for sample 1-0006.fastq
Does this mean that most of the HTs identified were not in the reference genome? You have mentioned that you discard HTs not in the reference genome which I think is not a valid assumption. For many bacterial species the reference genome is very old and hence there are genes/regions that cannot be found in the reference genome.  I think your pipeline needs to be modified in a way that it takes both a denovo assembled isolate genome and a reference genome. you can map back the reads to both the denovo assembled genome and the reference genome and make sure you are not getting rid of the sequences that are in the assembly.
2. Is there a way to identify which sample each tract belongs to using the tract_list.tsv?
3. What is .A. in the sequence reported by tract and ref_tract? e.g. ` GAAGATACCGCCTGTAGCGAAGCTG.A.GCGACTGCACGATCTGATATCCGGT` 
4. Why there are only a few HTs reported in the VCF file when we have dozens of HTs reported in tract_list.tsv?
5. Are the coordinates reported in the VCF file the isolate coordinates?
6. If there are mutations within the flanking regions of each HT, they will be recognized as different HTs?

**Comment by leomrtns** [comment]
Hello!
1. Yes, it means that the reference genome is not close enough to that particular sample. If you don't have a good reference then you can use your own _de novo_ one, assuming you have its annotations: tatajuba is compatible with the output from [prokka](https://github.com/tseemann/prokka)
2. The individual values per sample are in the `per_sample*` files. For instance `per_sample_average_length.tsv` will have, for each tract (**tract_id**), the average tract length for each column (=sample). The column **tract_id** can be used to find the tract information on `tract_list.tsv`
3. As described in https://github.com/quadram-institute-bioscience/tatajuba/tree/master/docs#list-of-hts , the `.A.` is the homopolymer (in this case, poly-A) --- notice that the homopolymer length is not hardcoded here since the assumption is that it may be variable, e.g. length 4 (AAAA) in one sample but length 3 (AAA) in another.
4. As we mention in https://github.com/quadram-institute-bioscience/tatajuba/tree/master/docs#list-of-hts , the file `tract_list.tsv` contains all tracts, even those that are constant across samples. The VCF file, on the other hand, contains only the locations where the particular sample differs from the reference.
5. The POS column is the 1-based location relative to the CHROM sequence in the reference genome (https://en.wikipedia.org/wiki/Variant_Call_Format)
6. No, provided they are within `-maxdist` and `-leven` distance they will be considered the same "context" (i.e. flanking region) even within a sample. And even when they have mutations between samples (or w.r.t. the reference) they will be merged as a single HT whenever the homopolymeric regions map to the same location in the reference. 

Notice that tatajuba was devised to describe variations between samples, and not between a single sample and a reference. You can circumvent this by providing the same sample several times (changing its file name)  :wink: 
However tatajuba does not report well the variation in the flanking regions: it selects the ones most similar to the reference, and even the VCF dismisses non-homopolymeric differences. For what you want you might need to use a regular variant caller, and then compare its output with the coordinates given by the BED file output by tatajuba (https://github.com/quadram-institute-bioscience/tatajuba/tree/master/docs#bed-file)

I hope it helps, and thanks for using tatajubá!

**Comment by mariaelf97** [comment]
Thank you for your response. After discussing your tool with our team we realized that the tool and the algorithms used are not designed for long read sequencing. We appreciate your response though!
